print("Peanut butter and ", end = "")
print("jelly")
print("10", "94", "40", sep=" --- ")
print("10", "94", "40", sep=" --- ", end=" # ")
print("Car")
print("Hello", "Goodbye",)
print("Hello", end=" & ")
print("Goodbye.")